## You can read more about all available flags and other environment variables here:
## https://help.penpot.app/technical-guide/configuration/#advanced-configuration

x-flags: &penpot-flags
  PENPOT_FLAGS: enable-smtp enable-prepl-server disable-onboarding
    disable-subscriptions-old enable-webhooks enable-email-verification
    disable-registration enable-login-with-oidc enable-oidc-registration

x-public-uri: &public-uri
  PENPOT_PUBLIC_URI: ${PUBLIC_URI}

x-redis-uri: &redis-uri
  PENPOT_REDIS_URI: ${REDIS_URI}

# networks:
#   penpot:

services:
  penpot-frontend:
    image: "penpotapp/frontend:2.14.5"
    restart: unless-stopped
    ports:
      - 10000:8080
    depends_on:
      - penpot-backend
      - penpot-exporter
    # networks:
    #   - penpot
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:80" ]
      interval: 2s
      timeout: 10s
      retries: 15
    environment:
      <<: *penpot-flags

  penpot-backend:
    image: "penpotapp/backend:2.14.5"
    restart: unless-stopped
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    # networks:
    #   - penpot
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:6060/readyz" ]
      interval: 2s
      timeout: 10s
      retries: 15
    environment:
      <<: [ *penpot-flags, *public-uri, *redis-uri ]

      ## If you going to uncomment this, we recommend to use a trully randomly generated
      ## 512 bits base64 encoded string here.  You can generate one with:
      ##
      ## python3 -c "import secrets; print(secrets.token_urlsafe(64))"

      PENPOT_SECRET_KEY: ${SECRET_KEY}

      ## The PREPL host. Mainly used for external programatic access to penpot backend
      ## (example: admin). By default it will listen on `localhost` but if you are going to use
      ## the `admin`, you will need to uncomment this and set the host to `0.0.0.0`.
      # PENPOT_PREPL_HOST: 0.0.0.0

      PENPOT_DATABASE_URI: ${DB_URI}
      PENPOT_DATABASE_USERNAME: ${DB_USERNAME}
      PENPOT_DATABASE_PASSWORD: ${DB_PASSWORD}

      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      PENPOT_OBJECTS_STORAGE_BACKEND: s3
      PENPOT_OBJECTS_STORAGE_S3_ENDPOINT: ${S3_ENDPOINT}
      PENPOT_OBJECTS_STORAGE_S3_REGION: ${S3_REGION}
      PENPOT_OBJECTS_STORAGE_S3_BUCKET: ${S3_BUCKET}

      PENPOT_TELEMETRY_ENABLED: false

      PENPOT_SMTP_DEFAULT_FROM: ${SMTP_FROM}
      PENPOT_SMTP_DEFAULT_REPLY_TO: ${SMTP_REPLY_TO}
      PENPOT_SMTP_HOST: ${SMTP_HOST}
      PENPOT_SMTP_PORT: ${SMTP_PORT}
      PENPOT_SMTP_USERNAME: ${SMTP_USERNAME}
      PENPOT_SMTP_PASSWORD: ${SMTP_PASSWORD}
      PENPOT_SMTP_TLS: ${SMTP_TLS:-false}
      PENPOT_SMTP_SSL: ${SMTP_SSL:-false}

      PENPOT_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      PENPOT_OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      PENPOT_OIDC_BASE_URI: ${OIDC_BASE_URI}
      PENPOT_OIDC_NAME: ${OIDC_NAME}

  penpot-exporter:
    image: "penpotapp/exporter:2.14.5"
    restart: unless-stopped
    # networks:
    #   - penpot
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:6061/readyz" ]
      interval: 2s
      timeout: 10s
      retries: 15
    environment:
      <<: *redis-uri
      PENPOT_SECRET_KEY: ${SECRET_KEY}
      # Don't touch it; this uses an internal docker network to communicate with the frontend.
      PENPOT_PUBLIC_URI: http://penpot-frontend:8080
