FROM penpotapp/frontend:latest

COPY ./legal-generated-html/* /var/www/app

RUN sed -i -e 's/https:\/\/penpot.app\/terms/https:\/\/design.zapal.tech\/terms-of-use.html/g' /var/www/app/js/shared.*.js
RUN sed -i -e 's/https:\/\/penpot.app\/privacy/https:\/\/design.zapal.tech\/privacy-policy.html/g' /var/www/app/js/shared.*.js

CMD ["nginx", "-g", "daemon off;"]
